### ISSUE TITLE
Breaking or Hitting Toggle

### ISSUE THREAD

**Issue by RJWadley** [MichaelHillcox/Auto-Clicker-Fabric#2]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the mod starts breaking blocks at my AFK farm. When I want it to hit mobs, I want it to hit mobs only, not start breaking the wall with my sword once all the mobs are dead.

**Describe the solution you'd like**
I think a good solution would be to implement a toggle in the settings between breaking/hitting/combined
When breaking is selected, the mod can hold down the button.
When hitting is selected, the mod will click without holding down the button.

**Describe alternatives you've considered**
The mod could use the tool in hand and what it's looking at to determine what the correct action is.

Hope this is resolved soon, fantastic mod.

**Comment by MichaelHillcox** [comment]
Seems simple enough, I'll look into it
